# Generated by Django 3.2 on 2024-02-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='heart',
            new_name='popular',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='heart',
            new_name='popular',
        ),
        migrations.RemoveField(
            model_name='album',
            name='category',
        ),
        migrations.RemoveField(
            model_name='album',
            name='musics',
        ),
        migrations.RemoveField(
            model_name='album',
            name='number_of_music',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='category',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='musics',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='number_of_music',
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.album'),
        ),
        migrations.AddField(
            model_name='music',
            name='number_listens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='playlist',
            field=models.ManyToManyField(related_name='music_playlist', to='music.Playlist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music.artist'),
        ),
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hearts',
            field=models.ManyToManyField(related_name='user_heart', to='music.Music'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
