# Generated by Django 3.2 on 2024-02-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20240219_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='playlist',
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('playist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
            ],
            options={
                'verbose_name': 'Playlist',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(related_name='playlist_item', through='music.PlaylistItem', to='music.Music'),
        ),
    ]
