# Generated by Django 3.2 on 2024-02-20 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20240220_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlistitem',
            options={'ordering': ['created_at'], 'verbose_name': 'Playlistitem'},
        ),
        migrations.CreateModel(
            name='ArtistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
            ],
            options={
                'verbose_name': 'ArtistItem',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='music',
            name='artist',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.ManyToManyField(through='music.ArtistItem', to='music.Artist'),
        ),
    ]
