# Generated by Django 3.2 on 2024-02-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='popular',
        ),
    ]
