# Generated by Django 3.2 on 2024-03-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20240229_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Follow'},
        ),
    ]
